### ISSUE TITLE
Issue using import_3dhela.py

### ISSUE THREAD

**Issue by icaoberg** [icaoberg/omepslid#6]
When I use `import_3dhela.py` I am getting this error

```
➜  omepslid git:(master) ✗ bash ./import_3dhela.sh
OMERO host [localhost]: 
OMERO port [4064]:
OMERO username [root]:
OMERO password [omero]:
Traceback (most recent call last):
  File "import_3dhela.py", line 581, in <module>
    main()
  File "import_3dhela.py", line 578, in main
    upload_3d_hela_collection(args.path, args.test)
  File "import_3dhela.py", line 560, in upload_3d_hela_collection
    conn = get_omero_connection()
  File "import_3dhela.py", line 158, in get_omero_connection
    conn = omero.gateway.BlitzGateway(username, password, host=host, port=port)
  File "/Users/icaoberg/Documents/code/omepslid/OMERO.py-5.2.2-ice35-b17/lib/python/omero/gateway/__init__.py", line 1479, in __init__
    self._resetOmeroClient()
  File "/Users/icaoberg/Documents/code/omepslid/OMERO.py-5.2.2-ice35-b17/lib/python/omero/gateway/__init__.py", line 1930, in _resetOmeroClient
    args=['--Ice.Config='+','.join(self.ice_config)])
  File "/Users/icaoberg/Documents/code/omepslid/OMERO.py-5.2.2-ice35-b17/lib/python/omero/__init__.py", line 67, in client
    return omero.clients.BaseClient(*args, **kwargs)
  File "/Users/icaoberg/Documents/code/omepslid/OMERO.py-5.2.2-ice35-b17/lib/python/omero/clients.py", line 140, in __init__
    self._initData(id)
  File "/Users/icaoberg/Documents/code/omepslid/OMERO.py-5.2.2-ice35-b17/lib/python/omero/clients.py", line 255, in _initData
    self.__ic = Ice.initialize(id)
  File "/Library/Python/2.7/site-packages/Ice.py", line 647, in initialize
    communicator = IcePy.Communicator(args, data)
Ice.PluginInitializationException: exception ::Ice::PluginInitializationException
{
    reason = unable to load entry point `IceSSL:createIceSSL': dlopen(libIceSSL.35.dylib, 10): image not found; dlopen(libIceSSL.35.so, 10): image not found; dlopen(libIceSSL.35.bundle, 10): image not found
}
```

Have you experienced this issue before?

**Comment by MarkMendell** [comment]
Yes, I remember now. The installation via the link I sent you was wrong. [This post](https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7853) is relevant.
1. Uninstall Ice. The DMG file you downloaded from [here](https://zeroc.com/distributions/ice/3.5/) has a script called `uninstall.sh` you can run to do that.
2. Install [homebrew](http://brew.sh/) if you don't have it.
3. Tap the OMERO homebrew tap: `$ brew tap ome/alt`.
4. Install python over brew if you haven't: `$ brew install python`. Note that you'll have to reinstall the modules for this python and make sure to run the script using this python. You can do this by running `/usr/local/bin/python` and `/usr/local/bin/pip` in place of `python` and `pip`.
5. Install OMERO's Ice with python bindings: `$ brew install zeroc-ice35 --with-python`
